name: Build ROMs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup WSL
      uses: Vampire/setup-wsl@v2.0.1
    - name: Download Asar 1.81
      run: invoke-webrequest https://github.com/RPGHacker/asar/releases/download/v1.81/asar181.zip | expand-archive
    - name: Run build
      run: wsl ASAR=asar171 make
    - name: Put artifacts in separate directory
      run: |
        mkdir artifacts
        mv supertanks.{smc,sym} artifacts
    - name: Upload rom
      uses: actions/upload-artifact@v3.1.2
      with:
        name: supertanks
        path: artifacts
        if-no-files-found: error
    - name: Clean up
      run: del /s /q artifacts
