name: Build ROMs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download Asar 1.81
      run: |
        $t = New-TemporaryFile | Rename-Item -NewName { $_ -replace 'tmp$', 'zip' } –PassThru
        Invoke-WebRequest -OutFile $t "https://github.com/RPGHacker/asar/releases/download/v1.81/asar181.zip"
        $t | Expand-Archive -DestinationPath asar181
        $t | rm
    - name: Display tree
      run: tree
    - name: Setup WSL
      uses: Vampire/setup-wsl@v2.0.1
    - name: Update WSL
      run: wsl -u root apt update
    - name: Install things
      run: wsl -u root apt install -y make python3
    - name: Display another tree
      run: wsl ls -Rl
    - name: Run build
      run: wsl ASAR=asar171 make
    - name: Put artifacts in separate directory
      run: |
        mkdir artifacts
        mv supertanks.{smc,sym} artifacts
    - name: Upload rom
      uses: actions/upload-artifact@v3.1.2
      with:
        name: supertanks
        path: artifacts
        if-no-files-found: error
    - name: Clean up
      run: del /s /q artifacts
